// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrbzDhgr7-gEsiZwi9oCjeQ2243jSEHOA',
    appId: '1:286397476192:web:d363e1140ae3d3ff794205',
    messagingSenderId: '286397476192',
    projectId: 'language-program-bc10c',
    authDomain: 'language-program-bc10c.firebaseapp.com',
    storageBucket: 'language-program-bc10c.firebasestorage.app',
    measurementId: 'G-4ZKFFRXBMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0Gg6Bw8VJCXzIz2A6Za4H6vNZy-jKo4',
    appId: '1:286397476192:android:a5cf98f65293ccc6794205',
    messagingSenderId: '286397476192',
    projectId: 'language-program-bc10c',
    storageBucket: 'language-program-bc10c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbcpJXWdTxeQyv9Lj_gXqv6u2o1RvgSG0',
    appId: '1:286397476192:ios:2b04df7aff37c5e9794205',
    messagingSenderId: '286397476192',
    projectId: 'language-program-bc10c',
    storageBucket: 'language-program-bc10c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbcpJXWdTxeQyv9Lj_gXqv6u2o1RvgSG0',
    appId: '1:286397476192:ios:2b04df7aff37c5e9794205',
    messagingSenderId: '286397476192',
    projectId: 'language-program-bc10c',
    storageBucket: 'language-program-bc10c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrbzDhgr7-gEsiZwi9oCjeQ2243jSEHOA',
    appId: '1:286397476192:web:38f5c131f09ef0c1794205',
    messagingSenderId: '286397476192',
    projectId: 'language-program-bc10c',
    authDomain: 'language-program-bc10c.firebaseapp.com',
    storageBucket: 'language-program-bc10c.firebasestorage.app',
    measurementId: 'G-ZZ8CF1Y706',
  );
}
